// <auto-generated />
using System;
using LojaVirtual.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaVirtual.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240418034014_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaVirtual.Domain.Entites.ClienteModel", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VendaModelIdVenda")
                        .HasColumnType("int");

                    b.Property<string>("nmCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.HasIndex("VendaModelIdVenda");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entites.ProdutoModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("DescricaoProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ValorUnitario")
                        .HasColumnType("real");

                    b.Property<int?>("VendaModelIdVenda")
                        .HasColumnType("int");

                    b.HasKey("IdProduto");

                    b.HasIndex("VendaModelIdVenda");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entites.VendaModel", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenda"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeVenda")
                        .HasColumnType("int");

                    b.Property<float>("ValorVenda")
                        .HasColumnType("real");

                    b.HasKey("IdVenda");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entites.ClienteModel", b =>
                {
                    b.HasOne("LojaVirtual.Domain.Entites.VendaModel", null)
                        .WithMany("Clientes")
                        .HasForeignKey("VendaModelIdVenda");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entites.ProdutoModel", b =>
                {
                    b.HasOne("LojaVirtual.Domain.Entites.VendaModel", null)
                        .WithMany("Produtos")
                        .HasForeignKey("VendaModelIdVenda");
                });

            modelBuilder.Entity("LojaVirtual.Domain.Entites.VendaModel", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
